-- Cutover Stage 2: wipe the 11,407 noisy excusals that the legacy
-- merged-sheet sync auto-generated by interpreting blank cells as
-- excusals. Manual excusals (source='manual') are preserved.
DELETE FROM excusals WHERE source = 'merged_sheet';
