-- Local / optional public fixtures only.
-- General HR sign-in user: create with Auth Admin API (no raw auth.users SQL):
--   npm run db:ensure-hr-user
-- Requires SUPABASE_SERVICE_ROLE_KEY + SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL) in .env.local.
